; PIC16F628A Configuration Bit Settings
; Assembly source line config statements
#include "p16f628a.inc"
; CONFIG
; __config 0xFF10
 __CONFIG _FOSC_INTOSCIO & _WDTE_OFF & _PWRTE_ON & _MCLRE_OFF & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _CP_OFF

 RES_VECT  CODE    0x0000            ; processor reset vector
	BSF STATUS,RP0
	BCF TRISB,0
	BCF TRISB,1
	BCF TRISB,2
	BCF STATUS,RP0
	MOVLW .7
	MOVWF CMCON
	BCF PORTB,0
	BCF PORTB,1
	BCF PORTB,2
	
  LE_CHAVE1
	BTFSS PORTA, 0
	GOTO APAGA_LED1
	BSF PORTB, 0
	GOTO LE_CHAVE2	
  APAGA_LED1
	BCF PORTB,0
	
  LE_CHAVE2
	BTFSS PORTA, 1
	GOTO APAGA_LED2
	BSF PORTB, 1
	GOTO LE_CHAVE3   
  APAGA_LED2
	BCF PORTB,1
	
  LE_CHAVE3
	BTFSS PORTA, 2
	GOTO APAGA_LED3
	BSF PORTB, 2
	GOTO LE_CHAVE1   
  APAGA_LED3
	BCF PORTB,2
	GOTO LE_CHAVE1
	
	END