; PIC16F628A Configuration Bit Settings
; Assembly source line config statements
#include "p16f628a.inc"
; CONFIG
; __config 0xFF70
 __CONFIG _FOSC_INTOSCIO & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _BOREN_ON & _LVP_OFF & _CPD_OFF & _CP_OFF
 
#define BANCO0	    BCF STATUS,RP0  ;ACESSO AO BANCO 0
#define BANCO1	    BSF STATUS,RP0  ;ACESSO AO BANCO 1
 
 CBLOCK 0x20			    ;VARIAVEIS
   FLAGS
   FILTRO
   CONTADOR
 ENDC
 
#define ACAO	    FLAGS,0	    ;ACAO COMO FLAG NO BIT 0
#define BOTAO	    PORTA,1	    ;BOTAO COMO ENTRADA PORT A, BIT 1
#define DISPLAY     PORTB	    ;DEFINE PORTAS B COMO SAIDA
 
V_FILTRO equ	    .100	    ;VALOR DO FILTRO
 
RES_VECT  CODE    0x0000            ; processor reset vector
    BANCO1			    ;ACESSA BANCO 1
    CLRF    TRISB		    ;TRANSFORMA TODOS B EM SAIDA
    BANCO0			    ;RETORNA AO BANCO 0
    MOVLW   .7			    ;DESATIVA COMPARADORES DE TENSAO
    MOVWF   CMCON
    CLRF    DISPLAY		    ;DESATIVA TODAS LUZES DO DISPLAY
    CLRF    CONTADOR		    ;CONTADOR = 0, CLRF LIMPA TODO O BYTE (BCF LIMPA O BIT)
    BCF	    ACAO		    ;LIMPA BIT DO ACAO
    MOVLW   V_FILTRO		    ;LIMPA O FILTRO
    MOVWF   V_FILTRO
    MOVLW   .254		    ;SETAR 0 NO DISPLAY NO INICIO
    MOVWF   DISPLAY
    
LE_BOTAO
    BTFSC   BOTAO		    ;VERIFICA SE BOTAO=0 (0 EH ACIONADO)
    GOTO    BOTAO_NAO_ACIONADO
    BTFSC   ACAO		    ;VERIFICA SE ACAO EH 0, AINDA NAO ACABOU A ACAO DE APERTAR
    GOTO    LE_BOTAO
    DECFSZ  FILTRO,F		    ;DIMINUI O FILTRO E VERIFICA SE EH 0
    GOTO    LE_BOTAO	
    BSF	    ACAO		    ;SETA 1 NO ACAO
    INCF    CONTADOR,F		    ;INCREMENTA NO CONTADOR
    ;VERIFICAR SE CONTADOR EH 10
    MOVLW   .10			    ;ADICONA 10 EM W
    SUBWF   CONTADOR,W		    ;W = CONTADOR - W
    BTFSC   STATUS,C		    ;SE C==0 RESULTADO NEGATIVO, OU SEJA, CONTADOR <10
				    ;SE C==1 RESULTADO POSITIVO, OU SEJA, CONTADOR >=10
    CLRF    CONTADOR		    ;LIMPA O BYTE DO CONTADOR
    MOVF    CONTADOR,W		    ;W = CONTADOR
    CALL    TABELA		    ;CHAMA A TABELA E PEGA O VALOR DE W CORRESPONDENTE
    MOVWF   DISPLAY		    ;MOSTRA NO DISPLAY O VALOR DE W, QUE EH O CONTADOR
    GOTO    LE_BOTAO
BOTAO_NAO_ACIONADO
    BCF	    ACAO
    MOVLW   V_FILTRO
    MOVWF   FILTRO
    GOTO    LE_BOTAO
    
TABELA
    ADDWF   PCL,F   ;DEFINE O INDICE (SALTO) DENTRO DA TABELA
    RETLW   .254    ;0
    RETLW   .56	    ;1
    RETLW   .221    ;2
    RETLW   .125    ;3
    RETLW   .59	    ;4
    RETLW   .119    ;5
    RETLW   .247    ;6
    RETLW   .60	    ;7
    RETLW   .255    ;8
    RETLW   .127    ;9
    
    

    
    
    
    
    
    
    
    
    
    
    
    
    END