#include "p16f628a.inc"
; CONFIG __config 0xFF18
 __CONFIG _FOSC_INTOSCIO & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _CP_OFF

#define	BANCO0	BCF STATUS,RP0
#define	BANCO1	BSF STATUS,RP0
 
    CBLOCK 0x20
	FILTRO
	FLAGS
    ENDC

#define	ACAO	FLAGS,0
;ENTRADAS
#define	BOTAO_M1H	PORTA,1
#define	BOTAO_M1AH	PORTA,2
#define	BOTAO_DESLIGA	PORTA,3
;SAIDAS
#define	M1H_LED1	PORTB,0  
#define	M1AH_LED2	PORTB,1
#define	DESLIGADO	PORTB,2
 
V_FILTRO    equ	    .200

RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    INICIO                   ; go to beginning of program
; TODO ADD INTERRUPTS HERE IF USED

MAIN_PROG CODE                      ; let linker place main program
INICIO
    BANCO1
    BCF	    TRISB,0
    BCF	    TRISB,1
    BCF	    TRISB,2
    BANCO0
    MOVLW   .7
    MOVWF   CMCON
    BCF	    M1H_LED1
    BCF	    ACAO
    MOVLW   V_FILTRO
    MOVWF   FILTRO
  
TESTABOTAOM1H
    BSF	    DESLIGADO
    BTFSC   BOTAO_M1H
    GOTO    NAO_PRESSIONADO
    BTFSC   ACAO
    GOTO    TESTABOTAOM1H
    DECFSZ  FILTRO,F
    GOTO    TESTABOTAOM1H
    BSF	    ACAO
    BSF	    M1H_LED1
    BCF	    DESLIGADO
    GOTO    TESTE_BOTAO_DESLIGADO
    
APAGA_LED    
    BCF	    M1H_LED1
    GOTO    TESTABOTAOM1H
    
NAO_PRESSIONADO
    BCF	    ACAO
    MOVLW   V_FILTRO
    MOVWF   FILTRO    
    GOTO    TESTABOTAOM1AH
    
TESTABOTAOM1AH
    BTFSC   BOTAO_M1AH
    GOTO    NAO_PRESSIONADO2
    BTFSC   ACAO
    GOTO    TESTABOTAOM1AH
    DECFSZ  FILTRO,F
    GOTO    TESTABOTAOM1AH
    BSF	    ACAO
    BSF	    M1AH_LED2
    BCF	    DESLIGADO
    GOTO    TESTE_BOTAO_DESLIGADO
    
TESTE_BOTAO_DESLIGADO
    BTFSC   BOTAO_DESLIGA
    GOTO    NAO_PRESSIONADO3
    BTFSC   ACAO
    GOTO    TESTE_BOTAO_DESLIGADO
    DECFSZ  FILTRO,F
    GOTO    TESTE_BOTAO_DESLIGADO
    BSF	    ACAO
    BSF	    DESLIGADO
    BCF	    M1H_LED1
    BCF	    M1AH_LED2
    GOTO    TESTABOTAOM1H
    
NAO_PRESSIONADO2
    BCF	    ACAO
    MOVLW   V_FILTRO
    MOVWF   FILTRO    
    GOTO    TESTABOTAOM1H
    
NAO_PRESSIONADO3
    BCF	    ACAO
    MOVLW   V_FILTRO
    MOVWF   FILTRO    
    GOTO    TESTE_BOTAO_DESLIGADO
    
    END